#SPLSUser客户端端口
server:
  port: 8082
#Eureka客户端相关配置
#连接注册中心的配置
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
#该服务在注册中心的名称
spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true
  #oracle数据库相关配置
  datasource:
    url: jdbc:oracle:thin:@10.1.12.223:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: p2p
    password: 123456
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1665924315@qq.com #发送邮件的邮箱地址
    password:  smhsnwxvqxbvchcc #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1665924315@qq.com # 发送邮件的地址，和上面username一致
    #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  #redis相关配置
  redis:
    host: 10.1.12.223
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  freemarker:
    cache: false
    suffix: .html
#mybatis相关配置
mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zl.pojo
  #开启自动下划线转驼峰命名
  configuration:
    map-underscore-to-camel-case: true
#连接外部服务超时配置    
ribbon: 
  ReadTimeout: 4000
  ConnectTimeout: 4000
hystrix: 
  command: 
    default:
      execution:
        timeout: 
          enabled: true
        isolation: 
          thread: 
            timeoutInMilliseconds: 5000